<?php

namespace ShopBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function CategoryRecherche($nom)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT e FROM ShopBundle:Category e
              
              WHERE
                e.category like :nom")
            ->setParameter('nom', $nom . '%')
            ->getResult();

    }

}
