<?php

namespace BlogBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function AjaxRecherche($str)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM BlogBundle:Blog e
                WHERE e.title LIKE :str'
            )
            ->setParameter('str', '%' . $str . '%')
            ->getResult();
    }
}
