<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTr0wnxw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTr0wnxw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTr0wnxw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTr0wnxw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTr0wnxw\appDevDebugProjectContainer([
    'container.build_hash' => 'Tr0wnxw',
    'container.build_id' => 'b7b75970',
    'container.build_time' => 1580304805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTr0wnxw');
