<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2rqnnv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2rqnnv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX2rqnnv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX2rqnnv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX2rqnnv\appDevDebugProjectContainer([
    'container.build_hash' => 'X2rqnnv',
    'container.build_id' => '79dac72b',
    'container.build_time' => 1581454070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2rqnnv');
